
# docker-sonar configuration,
# add this to your docker-compose up if you want to have sonarqube
# docker-compose -f docker-xcompose.yml -f docker-compose-sonar.yml up
version: "3"

services:
  sonar:
    image: sonarqube
    depends_on: # start  proxy after all the others
      - postgres
    extra_hosts:
      - ${DC_HOSTNAME}:${DC_HOSTIP}
    networks:
       - devstacknetwork
    environment:
      # the Default User and Passwort for Postgress is sonar/sonar in the
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ${DC_BASE_DATA_DIR}/sonar/sonarqube_conf:/opt/sonarqube/conf
      - ${DC_BASE_DATA_DIR}/sonar/sonarqube_data:/opt/sonarqube/data
      - ${DC_BASE_DATA_DIR}/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ${DC_BASE_DATA_DIR}/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
